apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: 539188695824.dkr.ecr.ap-south-1.amazonaws.com/backend:sha-fc6a9555f89ca876ce77c2c04cbe0620bbda4c91
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: devsecops-project-db.cn4nwgavkaom.ap-south-1.rds.amazonaws.com
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: tS<4>tP[Hi~I4<dso32_jWM7uxCN
